# Generated by Django 5.0.1 on 2024-01-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0002_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='user_id',
        ),
    ]
